upstream flask_app {
    server web-1:5000;
    server web-2:5000;
    server web-3:5000;
}

server {
    listen 80;

    location / {
        proxy_pass http://flask_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }

    location /nginx_status {
        stub_status on;
    }
}
